# Constants
API_URL = "https://bulbapedia.bulbagarden.net/w/api.php"
HEADERS = {
    "User-Agent": "Mounir Rouibi from University Jean Monnet (mohamed.rouibi@etu.univ-st-etienne.fr)"
}
SPARQL_ENDPOINT = "http://localhost:3030/dataset/sparql"

INFOBOXES_TEMPLATES = [
    "Template:AbilityInfobox",
    "Template:AbilityInfobox/desc",
    "Template:AbilityInfobox/header",
    "Template:AbilityInfoboxNoncat",
    "Template:AdvArcInfobox",
    "Template:AnimeLocationInfobox",
    "Template:AnimePokémonInfobox",
    "Template:ArchetypeInfobox",
    "Template:BadgeInfobox",
    "Template:BattleEInfobox",
    "Template:BattleEInfobox/Prize",
    "Template:BattrioExpansionInfobox",
    "Template:BattrioPuckInfobox",
    "Template:BerryInfobox",
    "Template:Blueinfobox",
    "Template:Boardgame Infobox",
    "Template:BookInfobox",
    "Template:CDInfobox",
    "User:Celadonkey/PokemonInfobox",
    "Template:ChapInfobox",
    "Template:Chapterinfobox",
    "Template:Character Infobox",
    "Template:Character Infobox/Anime",
    "Template:Character Infobox/Game",
    "Template:Character Infobox/Manga",
    "Template:Character Infobox/Team",
    "Template:CharInfobox",
    "Template:CharInfoboxUser",
    "Template:Company Infobox",
    "Template:Console infobox",
    "Template:CountryInfobox",
    "Template:DeckInfobox",
    "Template:DuelInfobox",
    "Template:DuelInfobox/Figure",
    "Template:DuelInfobox/Footer",
    "Template:DuelInfobox/Header",
    "Template:Dungeon infobox",
    "Template:DWGame",
    "Template:DWInfobox",
    "User:Ebrunborg/Template:Pokémon Infobox",
    "Template:EnergyCardInfobox",
    "Template:EpisodeInfobox",
    "Template:EpisodeInfobox2",
    "Draft:EpisodeInfoboxShort",
    "Template:EpisodeInfoboxSpecial",
    "Template:FA Infobox",
    "Template:Facility infobox",
    "Template:Fan site",
    "User:FinnishPokéFan92/Template:Facility Infobox",
    "Template:Ga-OleInfobox",
    "Template:GenInfo",
    "Template:GlitchMoveInfobox",
    "Template:GlitchPkmnInfobox",
    "Template:GlitchPkmnInfoboxNocat",
    "Template:GlitchSpriteBox",
    "Template:GymInfobox",
    "Template:IllustStoryInfobox",
    "Template:Infobox game",
    "Template:Infobox island",
    "Template:Infobox location",
    "Template:Infobox walkthrough",
    "Template:Infobox zone",
    "Template:InfoboxBlock",
    "Template:InfoboxTV",
    "Template:Item",
    "Template:Item/I",
    "Template:ItemInfobox/BagRow",
    "Template:ItemInfobox/BagRowBottom",
    "Template:ItemInfobox/Flavor",
    "Template:ItemInfobox/FlavorRow",
    "Template:ItemInfobox/Fling",
    "Template:ItemInfobox/FlingEffect",
    "Template:ItemInfobox/foot",
    "Template:ItemInfobox/head",
    "Template:ItemInfobox/MD",
    "Template:ItemInfobox/NaturalGift",
    "Template:ItemInfobox/NaturalGift/6",
    "Template:KingdomInfobox",
    "User:Kogoro/SeasonInfobox",
    "Template:MagazineInfobox",
    "Template:MastersChapInfobox",
    "Template:MastersEventInfobox",
    "Template:MastersInfobox",
    "Template:MastersSkillInfobox",
    "Template:MDMoveInfobox",
    "Template:Merchandise Infobox",
    "Template:MerchCollectionInfobox",
    "Template:MezastarInfobox",
    "User:MisterE13/Template:BattrioPuckInfobox",
    "Template:MoveInfobox",
    "Template:MoveInfoboxNoncat",
    "Template:MovieInfobox",
    "Template:Mystery Dungeon location",
    "User:Nairbnroh/Sandbox",
    "User:Nescientist/Template:MoveInfobox",
    "Template:NintendoService",
    "Template:Podcast",
    "Template:PokkénInfobox",
    "Template:Pokémon Center Infobox",
    "Template:Pokémon Infobox",
    "Template:Pokémon Infobox/GO",
    "Template:PokémoncardInfobox",
    "Template:PokémoncardInfobox/Expansion",
    "Template:PokémoncardInfobox/Footer",
    "Template:PokémonInfobox",
    "Template:PokémonInfoboxNoncat",
    "Template:PokéstarMovie",
    "Template:PokéWalkerInfobox",
    "Template:RangerLocationInfobox",
    "Template:RegionInfobox",
    "Template:Ribbon",
    "User:Romanoff Blitzer/Sandbox",
    "Template:Route infobox",
    "User:SaturnMario/Template:GOSeasonInfobox",
    "Template:Season Infobox",
    "Template:Season Infobox/EpiEntry",
    "Template:Season Infobox/EpiFooter",
    "Template:Season Infobox/EpiHeader",
    "Template:SeasonInfobox",
    "Template:SkyEpInfobox",
    "Template:SleepIsland",
    "Template:Song",
    "Template:TCGEnergyCardInfobox",
    "Template:TCGEnergyCardInfobox/Expansion",
    "Template:TCGEnergyCardInfobox/Footer",
    "Template:TCGEnergyCardInfobox/ReleaseInfo",
    "Template:TCGExpansionInfobox",
    "Template:TCGGBInfobox",
    "Template:TCGPocketDeckInfobox",
    "Template:TCGPocketEventInfobox",
    "Template:TCGPocketExpansionInfobox",
    "Template:TCGPromoInfobox",
    "Template:TCGTrainerCardInfobox",
    "Template:TCGTrainerCardInfobox/Expansion",
    "Template:TCGTrainerCardInfobox/Footer",
    "Template:TCGTrainerCardInfobox/Fossil",
    "Template:TCGTrainerCardInfobox/ReleaseInfo",
    "Template:Team Infobox",
    "User:TehPerson/MoveInfobox",
    "Template:TFGCardInfobox",
    "Template:TFGCardInfobox/Expansion",
    "Template:TFGCrystalInfobox",
    "Template:TFGInfobox",
    "Template:TFGInfobox/Footer",
    "Template:TFGInfobox/Trainer",
    "Template:TFGPearlInfobox",
    "Template:Theme Park Infobox",
    "User:Tiddlywinks/AdvInfo",
    "User:Tiddlywinks/AdvInfo/footer",
    "User:Tiddlywinks/AdvInfo/header",
    "User:Tiddlywinks/AdvInfo/pubrow",
    "User:Tiddlywinks/Template:MoveInfobox",
    "Template:TournamentInfobox",
    "Template:Town infobox",
    "Template:TrainercardInfobox",
    "Template:TrainerClassInfobox",
    "Template:TrettaInfobox",
    "Template:TrettaSetInfobox",
    "Template:Trozei location infobox",
    "User:Umeko/Template:CharInfobox",
    "Template:UniteInfobox",
    "Template:UserPokémonInfobox",
    "Template:VolumeInfobox",
    "Template:WarlordInfobox",
    "Template:WarriorInfobox",
    "Template:WeatherInfobox"
]

famous_templates = [
    "Pokémon Infobox",        # Central infobox for Pokémon species
    "MoveInfobox",           # Infobox for moves
    "ItemInfobox",           # Infobox for items
    "Character Infobox",     # Infobox for characters
    "RegionInfobox",         # Infobox for Pokémon regions
    "EpisodeInfobox",        # Infobox for anime episodes
    "EpisodeInfobox2",       # Alternate anime episode infobox
    "PokémoncardInfobox",    # Infobox for Pokémon trading cards
    "Season Infobox",        # Infobox for seasons
    "GameInfobox",           # Infobox for games
    "AnimeLocationInfobox",  # Infobox for anime-specific locations
    "BadgeInfobox",          # Infobox for gym badges
    "Town infobox",          # Infobox for towns in Pokémon world
    "Merchandise Infobox",   # Infobox for Pokémon merchandise
    "TCGTrainerCardInfobox", # Infobox for TCG trainer cards
    "Facility infobox",      # Infobox for game facilities
    "Mystery Dungeon location", # Infobox for Mystery Dungeon locations
    "TCGExpansionInfobox"    # Infobox for Pokémon TCG expansions
]


